-- Generated by Oracle SQL Developer Data Modeler 24.3.0.240.1210
--   at:        2024-12-21 12:26:16 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE adresa (
    id_adr     INTEGER NOT NULL,
    ul_adr     VARCHAR2(100),
    rbr_adr    INTEGER,
    grad_id_gr INTEGER NOT NULL
);

ALTER TABLE adresa ADD CONSTRAINT adresa_pk PRIMARY KEY ( id_adr );

CREATE TABLE agent (
    ig_age       INTEGER NOT NULL,
    ime_age      VARCHAR2(50),
    prz_age      VARCHAR2(50),
    email_age    VARCHAR2(100),
    agent_ig_age INTEGER
);

ALTER TABLE agent ADD CONSTRAINT agent_pk PRIMARY KEY ( ig_age );

CREATE TABLE angažuje (
    agent_ig_age      INTEGER NOT NULL,
    stanodavac_id_kor INTEGER NOT NULL
);

ALTER TABLE angažuje ADD CONSTRAINT angažuje_pk PRIMARY KEY ( agent_ig_age,
                                                              stanodavac_id_kor );

CREATE TABLE grad (
    id_gr  INTEGER NOT NULL,
    naz_gr VARCHAR2(50)
);

ALTER TABLE grad ADD CONSTRAINT grad_pk PRIMARY KEY ( id_gr );

CREATE TABLE kategorija (
    id_kat  INTEGER NOT NULL,
    naz_kat VARCHAR2(50)
);

ALTER TABLE kategorija ADD CONSTRAINT kategorija_pk PRIMARY KEY ( id_kat );

CREATE TABLE korisnik (
    id_kor        INTEGER NOT NULL,
    ime_kor       VARCHAR2(50),
    prz_kor       VARCHAR2(50),
    email_kor     VARCHAR2(100),
    tip_kor       VARCHAR2(10),
    korisnik_type VARCHAR2(10) NOT NULL
);

ALTER TABLE korisnik
    ADD CONSTRAINT ch_inh_korisnik CHECK ( korisnik_type IN ( 'Stanodavac', 'Zakupac' ) );

ALTER TABLE korisnik ADD CONSTRAINT korisnik_pk PRIMARY KEY ( id_kor );

CREATE TABLE opremljenost (
    id_opr   INTEGER NOT NULL,
    nivo_opr VARCHAR2(50),
    opis_opr VARCHAR2(1000)
);

ALTER TABLE opremljenost ADD CONSTRAINT opremljenost_pk PRIMARY KEY ( id_opr );

CREATE TABLE poruka (
    id_por           INTEGER NOT NULL,
    sadr_por         VARCHAR2(2000) NOT NULL,
    pos_por          INTEGER,
    prim_por         INTEGER,
    korisnik_id_kor2 INTEGER NOT NULL,
    korisnik_id_kor  INTEGER NOT NULL
);

ALTER TABLE poruka ADD CONSTRAINT poruka_pk PRIMARY KEY ( id_por );

CREATE TABLE prostorija (
    id_pros    INTEGER NOT NULL,
    naz_pros   VARCHAR2(50),
    povr_pros  INTEGER,
    stan_id_st INTEGER NOT NULL
);

ALTER TABLE prostorija ADD CONSTRAINT prostorija_pk PRIMARY KEY ( id_pros,
                                                                  stan_id_st );

CREATE TABLE pružalac_usluga (
    id_pru       INTEGER NOT NULL,
    ime_pru      VARCHAR2(50),
    kont_inf_pru VARCHAR2(100),
    naz_usl_pru  VARCHAR2(50)
);

ALTER TABLE pružalac_usluga ADD CONSTRAINT pružalac_usluga_pk PRIMARY KEY ( id_pru );

CREATE TABLE račun (
    id_rac                 INTEGER NOT NULL,
    izn_rac                NUMBER(10, 2),
    plac_rac               VARCHAR2(2),
    dat_dosp_rac           DATE,
    rok_isp_rac            DATE,
    pružalac_usluga_id_pru INTEGER NOT NULL
);

ALTER TABLE račun ADD CONSTRAINT račun_pk PRIMARY KEY ( id_rac,
                                                        pružalac_usluga_id_pru );

CREATE TABLE recenzija (
    id_rec               INTEGER NOT NULL,
    tekst_rec            VARCHAR2(200),
    ocena_rec            NUMBER(3, 2),
    zakup_rec            INTEGER,
    stan_rec             INTEGER NOT NULL,
    stanod_rec           INTEGER,
    sklapaju_sklapaju_id NUMBER NOT NULL
);

CREATE UNIQUE INDEX recenzija__idx ON
    recenzija (
        sklapaju_sklapaju_id
    ASC );

ALTER TABLE recenzija ADD CONSTRAINT recenzija_pk PRIMARY KEY ( id_rec );

CREATE TABLE sklapaju (
    stanod_id         INTEGER,
    zak_id            INTEGER,
    agent_ig_age      INTEGER,
    stan_id_st        INTEGER NOT NULL,
    zakupac_id_kor    INTEGER NOT NULL,
    stanodavac_id_kor INTEGER NOT NULL,
    sklapaju_id       NUMBER NOT NULL
);

ALTER TABLE sklapaju ADD CONSTRAINT sklapaju_pk PRIMARY KEY ( sklapaju_id );

CREATE TABLE stan (
    id_st               INTEGER NOT NULL,
    povr_st             INTEGER,
    cena_st             INTEGER,
    ocena_st            INTEGER,
    dostup_st           VARCHAR2(3),
    adresa_id_adr       INTEGER NOT NULL,
    kategorija_id_kat   INTEGER NOT NULL,
    opremljenost_id_opr INTEGER NOT NULL,
    stanodavac_id_kor   INTEGER NOT NULL
);

ALTER TABLE stan ADD CONSTRAINT stan_pk PRIMARY KEY ( id_st );

CREATE TABLE stanodavac (
    id_kor       INTEGER NOT NULL,
    ocena_stanod NUMBER(3, 2)
);

ALTER TABLE stanodavac ADD CONSTRAINT stanodavac_pk PRIMARY KEY ( id_kor );

CREATE TABLE ugovor_o_zakupu (
    id_ug                INTEGER NOT NULL,
    dat_poc_ug           DATE,
    dat_kr_ug            DATE,
    zakup_ug             INTEGER,
    stan_ug              INTEGER,
    stanod_ug            INTEGER,
    agnt_ug              INTEGER,
    status_ug            VARCHAR2(2),
    stan_id_st           INTEGER NOT NULL,
    sklapaju_sklapaju_id NUMBER NOT NULL
);

CREATE UNIQUE INDEX ugovor_o_zakupu__idx ON
    ugovor_o_zakupu (
        sklapaju_sklapaju_id
    ASC );

ALTER TABLE ugovor_o_zakupu ADD CONSTRAINT ugovor_o_zakupu_pk PRIMARY KEY ( id_ug );

CREATE TABLE usluzivanje (
    stan_id_st             INTEGER NOT NULL,
    pružalac_usluga_id_pru INTEGER NOT NULL
);

ALTER TABLE usluzivanje ADD CONSTRAINT usluzivanje_pk PRIMARY KEY ( stan_id_st,
                                                                    pružalac_usluga_id_pru );

CREATE TABLE zahtev_za_obilazak (
    id_obi         INTEGER NOT NULL,
    datvr_obi      DATE,
    kor_obi        INTEGER,
    stan_obi       INTEGER,
    status_obi     VARCHAR2(2),
    agent_ig_age   INTEGER NOT NULL,
    stan_id_st     INTEGER NOT NULL,
    zakupac_id_kor INTEGER NOT NULL
);

ALTER TABLE zahtev_za_obilazak ADD CONSTRAINT zahtev_za_obilazak_pk PRIMARY KEY ( id_obi );

CREATE TABLE zakupac (
    id_kor   INTEGER NOT NULL,
    pref_zak VARCHAR2(200)
);

ALTER TABLE zakupac ADD CONSTRAINT zakupac_pk PRIMARY KEY ( id_kor );

ALTER TABLE adresa
    ADD CONSTRAINT adresa_grad_fk FOREIGN KEY ( grad_id_gr )
        REFERENCES grad ( id_gr );

ALTER TABLE agent
    ADD CONSTRAINT agent_agent_fk FOREIGN KEY ( agent_ig_age )
        REFERENCES agent ( ig_age );

ALTER TABLE angažuje
    ADD CONSTRAINT angažuje_agent_fk FOREIGN KEY ( agent_ig_age )
        REFERENCES agent ( ig_age );

ALTER TABLE angažuje
    ADD CONSTRAINT angažuje_stanodavac_fk FOREIGN KEY ( stanodavac_id_kor )
        REFERENCES stanodavac ( id_kor );

ALTER TABLE poruka
    ADD CONSTRAINT poruka_korisnik_fk FOREIGN KEY ( korisnik_id_kor )
        REFERENCES korisnik ( id_kor );

ALTER TABLE poruka
    ADD CONSTRAINT poruka_korisnik_fkv2 FOREIGN KEY ( korisnik_id_kor2 )
        REFERENCES korisnik ( id_kor );

ALTER TABLE prostorija
    ADD CONSTRAINT prostorija_stan_fk FOREIGN KEY ( stan_id_st )
        REFERENCES stan ( id_st );

ALTER TABLE račun
    ADD CONSTRAINT račun_pružalac_usluga_fk FOREIGN KEY ( pružalac_usluga_id_pru )
        REFERENCES pružalac_usluga ( id_pru );

ALTER TABLE recenzija
    ADD CONSTRAINT recenzija_sklapaju_fk FOREIGN KEY ( sklapaju_sklapaju_id )
        REFERENCES sklapaju ( sklapaju_id );

ALTER TABLE sklapaju
    ADD CONSTRAINT sklapaju_agent_fk FOREIGN KEY ( agent_ig_age )
        REFERENCES agent ( ig_age );

ALTER TABLE sklapaju
    ADD CONSTRAINT sklapaju_stan_fk FOREIGN KEY ( stan_id_st )
        REFERENCES stan ( id_st );

ALTER TABLE sklapaju
    ADD CONSTRAINT sklapaju_stanodavac_fk FOREIGN KEY ( stanodavac_id_kor )
        REFERENCES stanodavac ( id_kor );

ALTER TABLE sklapaju
    ADD CONSTRAINT sklapaju_zakupac_fk FOREIGN KEY ( zakupac_id_kor )
        REFERENCES zakupac ( id_kor );

ALTER TABLE stan
    ADD CONSTRAINT stan_adresa_fk FOREIGN KEY ( adresa_id_adr )
        REFERENCES adresa ( id_adr );

ALTER TABLE stan
    ADD CONSTRAINT stan_kategorija_fk FOREIGN KEY ( kategorija_id_kat )
        REFERENCES kategorija ( id_kat );

ALTER TABLE stan
    ADD CONSTRAINT stan_opremljenost_fk FOREIGN KEY ( opremljenost_id_opr )
        REFERENCES opremljenost ( id_opr );

ALTER TABLE stan
    ADD CONSTRAINT stan_stanodavac_fk FOREIGN KEY ( stanodavac_id_kor )
        REFERENCES stanodavac ( id_kor );

ALTER TABLE stanodavac
    ADD CONSTRAINT stanodavac_korisnik_fk FOREIGN KEY ( id_kor )
        REFERENCES korisnik ( id_kor );

ALTER TABLE ugovor_o_zakupu
    ADD CONSTRAINT ugovor_o_zakupu_sklapaju_fk FOREIGN KEY ( sklapaju_sklapaju_id )
        REFERENCES sklapaju ( sklapaju_id );

ALTER TABLE ugovor_o_zakupu
    ADD CONSTRAINT ugovor_o_zakupu_stan_fk FOREIGN KEY ( stan_id_st )
        REFERENCES stan ( id_st );

ALTER TABLE usluzivanje
    ADD CONSTRAINT usluzivanje_pružalac_usluga_fk FOREIGN KEY ( pružalac_usluga_id_pru )
        REFERENCES pružalac_usluga ( id_pru );

ALTER TABLE usluzivanje
    ADD CONSTRAINT usluzivanje_stan_fk FOREIGN KEY ( stan_id_st )
        REFERENCES stan ( id_st );

ALTER TABLE zahtev_za_obilazak
    ADD CONSTRAINT zahtev_za_obilazak_agent_fk FOREIGN KEY ( agent_ig_age )
        REFERENCES agent ( ig_age );

ALTER TABLE zahtev_za_obilazak
    ADD CONSTRAINT zahtev_za_obilazak_stan_fk FOREIGN KEY ( stan_id_st )
        REFERENCES stan ( id_st );

ALTER TABLE zahtev_za_obilazak
    ADD CONSTRAINT zahtev_za_obilazak_zakupac_fk FOREIGN KEY ( zakupac_id_kor )
        REFERENCES zakupac ( id_kor );

ALTER TABLE zakupac
    ADD CONSTRAINT zakupac_korisnik_fk FOREIGN KEY ( id_kor )
        REFERENCES korisnik ( id_kor );

CREATE OR REPLACE TRIGGER arc_fkarc_3_stanodavac BEFORE
    INSERT OR UPDATE OF id_kor ON stanodavac
    FOR EACH ROW
DECLARE
    d VARCHAR2(10);
BEGIN
    SELECT
        a.korisnik_type
    INTO d
    FROM
        korisnik a
    WHERE
        a.id_kor = :new.id_kor;

    IF ( d IS NULL OR d <> 'Stanodavac' ) THEN
        raise_application_error(-20223, 'FK Stanodavac_Korisnik_FK in Table Stanodavac violates Arc constraint on Table Korisnik - discriminator column Korisnik_TYPE doesn''t have value ''Stanodavac'''
        );
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;
/

CREATE OR REPLACE TRIGGER arc_fkarc_3_zakupac BEFORE
    INSERT OR UPDATE OF id_kor ON zakupac
    FOR EACH ROW
DECLARE
    d VARCHAR2(10);
BEGIN
    SELECT
        a.korisnik_type
    INTO d
    FROM
        korisnik a
    WHERE
        a.id_kor = :new.id_kor;

    IF ( d IS NULL OR d <> 'Zakupac' ) THEN
        raise_application_error(-20223, 'FK Zakupac_Korisnik_FK in Table Zakupac violates Arc constraint on Table Korisnik - discriminator column Korisnik_TYPE doesn''t have value ''Zakupac'''
        );
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;
/

CREATE SEQUENCE sklapaju_sklapaju_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER sklapaju_sklapaju_id_trg BEFORE
    INSERT ON sklapaju
    FOR EACH ROW
    WHEN ( new.sklapaju_id IS NULL )
BEGIN
    :new.sklapaju_id := sklapaju_sklapaju_id_seq.nextval;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            19
-- CREATE INDEX                             2
-- ALTER TABLE                             46
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           3
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          1
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
